# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 12:50
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, null=True)),
                ('category_keywords', models.CharField(max_length=255, null=True)),
                ('category_description', models.CharField(max_length=255, null=True)),
                ('seo_url', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Seo_URL : (Auto)')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('time', models.DateTimeField(null=True)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('keywords', models.CharField(max_length=255, null=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('seo_url', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Seo_URL : (Auto)')),
                ('is_active', models.BooleanField(default=False)),
                ('category_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApplication.category')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
