# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApplication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='seo_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL : (Auto)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BlogApplication.Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='seo_url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL : (Auto)'),
        ),
    ]
